name: Update data.json

on:
  push:
    paths:
      - 'tv-conteudo/**'
      - '.github/workflows/atualizar-json.yml'
      - 'gerar-json.js'

jobs:
  gerar-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: false


      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Executar script e gerar data.json
        run: node gerar-json.js

      - name: Commit e push do data.json
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name "github-actions"
    git config --global user.email "github-actions@users.noreply.github.com"
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
    git pull origin ${{ github.ref_name }}
    git add tv-conteudo/data.json
    git commit -m "Atualizando data.json automaticamente" || echo "Nada para commitar"
    git push origin HEAD:${{ github.ref_name }}

