
name: Atualizar data.json

on:
  push:
    paths:
      - 'tv-conteudo/imagens/**'
      - 'tv-conteudo/videos/**'
      - '.github/workflows/**'
      - 'gerar-json.js'

jobs:
  gerar-json:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Gerar data.json
        run: node gerar-json.js

      - name: Commit e push do data.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tv-conteudo/data.json
          git commit -m "🔁 Atualizando data.json automaticamente" || echo "Nenhuma alteração"
          git push
