name: Atualizar data.json

on:
  push:
    paths:
      - 'tv-conteudo/**'
  workflow_dispatch:

jobs:
  gerar-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Executar script para gerar data.json
        run: node gerar-json.js

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push do data.json
        run: |
          git add tv-conteudo/data.json
          git commit -m "Atualização automática do data.json"
          git push
